### ISSUE TITLE
Add support for onChange callbacks for zoom, pan

### ISSUE THREAD

**Issue by brentoneill** [chrvadala/react-svg-pan-zoom#30]
Would be nice to have some sort of callback to hook in to for zoom and pan events. 

For example, when I pan my `<svg>` "paper", I want to move an `html` based menu that lies outside of the `<svg>` "paper" as I pan the `<svg>` paper. Currently, I have no way of knowing when the pan is occurring and when it completes. 

I propose adding: `onZoom` and `onPan` as props for the `ReactSVGPanZoom` component and passing back the scaleFactor and translateX/translateY properties respectively.

Happy to put up a PR that handles this.

**Comment by chrvadala** [comment]
I Agree. It could be a very useful feature.
If you have enough time to develop it go on with the PR.


> component and passing back the scaleFactor and translateX/translateY properties respectively.
Instead of this I suggest to pass back the `viewerEvent` instance, because it calculate those  informations only when requested (lazy load), moreover it has a lot of additional information that could be useful to the developer.

How to intend to pass the zoom/pan action that now is only known by the interactions.js module to the viewer that should invoke those callback?

**Comment by brentoneill** [comment]
Working on this now - our org needs these features with your awesome plugin 👍 

I was planning on adding a function to check for these callbacks and pass through the desired params, probably inside `Viewer.handleViewerEvent`

**Comment by chrvadala** [comment]
In progress here https://github.com/chrvadala/react-svg-pan-zoom/pull/75

**Comment by chrvadala** [comment]
Introduced in version 2.16.0
