### ISSUE TITLE
Add a prop for zoom min/max

### ISSUE THREAD

**Issue by brentoneill** [chrvadala/react-svg-pan-zoom#31]
Would be nice to add a prop to the `ReactSVGPanZoom` component that allows you to set the min/max scaleFactor.

Happy to put up a PR that handles this.

**Comment by chrvadala** [comment]
I guess that to develop it we need to close this #30

**Comment by brentoneill** [comment]
going to include this with #30

**Comment by vanthiyathevan** [comment]
Any update on when this one?

**Comment by chrvadala** [comment]
Hi @vanthiyathevan, at this moment, I'm not working on it, because I'm spending my free time on another open source project https://github.com/chrvadala/transformation-matrix/pull/9
Some users started a PR (https://github.com/chrvadala/react-svg-pan-zoom/pull/34), but unfortunately it has not completed.
Inside this PR there is a good part of this feature. Feel free to take care of it.

**Comment by chrvadala** [comment]
In progress in https://github.com/chrvadala/react-svg-pan-zoom/pull/71

**Comment by chrvadala** [comment]
Released with v2.15.0
