### ISSUE TITLE
AutoSizer doesn't work

### ISSUE THREAD

**Issue by LogicMonsters** [chrvadala/react-svg-pan-zoom#47]
Can anyone help with this, when I try to integrate AutoSizer, it doesn't work. and shows: 

> _**Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `StadiumMap`.**_

And here is the code snippet in StadiumMap.js file (almost the same as the [examplel](https://github.com/chrvadala/react-svg-pan-zoom/blob/master/docs/autosizer-viewer.md)
```
import { ReactSVGPanZoom, AutoSizer } from 'react-svg-pan-zoom';
...
render () {
  return (
  <AutoSizer>
       {({width, height}) => width === 0 || height === 0 ? null : (
        <ReactSVGPanZoom
          width={512} height={384}
          className="svg-pan-zoom-wrapper"
          style={{ outline: "1px solid black" }}
          ref={Viewer => this.Viewer = Viewer}
        >
           <svg  ...> ... </svg>
        </ReactSVGPanZoom>
      )}
 </AutoSizer>
)}

export default connect(mapStateToProps, { setCurSection })(StadiumMap);
```
Outside the componet **StadiumMap**, it is wrapped by 
`<div className="row"><div className="col-md-7"><StadiumMap /></div></div>`

**Comment by chrvadala** [comment]
Autosizer isn't part of this library, but it's a component of react-virtualized. I gonna add this info on the wiki page https://github.com/chrvadala/react-svg-pan-zoom/blob/master/docs/autosizer-viewer.md, because actually isn't enough clear.
Moreover a full example is already available here https://github.com/chrvadala/react-svg-pan-zoom/blob/master/storybook/stories/AutosizerViewer.jsx#L4

**Comment by chrvadala** [comment]
@LogicMonsters can we close this?

**Comment by LogicMonsters** [comment]
@chrvadala Yes, yes, sure. Sorry for late response !
