### ISSUE TITLE
What does preventPanOutside actually do?

### ISSUE THREAD

**Issue by cassln** [chrvadala/react-svg-pan-zoom#85]
Hello!

Seems like on/off `preventPanOutside` does not affect anything in [this demo](https://chrvadala.github.io/react-svg-pan-zoom/?knob-detectAutoPan=true&knob-detectWheel=true&knob-detectPinchGesture=true&knob-preventPanOutside=true&selectedKind=React%20SVG%20Pan%20Zoom&selectedStory=Autosizer%20viewer&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs).

I expected leaflet-like-pan behavior with `preventPanOutside=false`: while panning and cursor moves outside, panning will not be interrupted. You can try it on the [leaflet main page](http://leafletjs.com/index.html).

Is that a bug, or this option has another purpose?

**Comment by chrvadala** [comment]
This feature avoids that the user drag and drop the image outside the viewer and doesn't refer with the ability to pan the image also if the user has the mouse pointer outside the container.
I think that to have a leaflet like pan feature we need to rewrite this library attaching the mouse move event on the global document instead of the react component. 
It could be a bit tricky and might break some other components on the same page.
